apiVersion: v1
kind: Service
metadata:
  name: nginx-service
spec:
  selector:
    app: nginx
  ports:
    - protocol: TCP
      name: http
      port: 80
      targetPort: 80
      nodePort: 30080  # NodePortとして使用するポート番号
    - protocol: TCP
      name: proxy
      port: 3128
      targetPort: 3128
      nodePort: 30180
  type: NodePort
