apiVersion: v1
kind: Service
metadata:
  name: pgadmin-service
spec:
  selector:
    app: pgadmin
  ports:
    - protocol: TCP
      port: 81
      targetPort: 81
      nodePort: 30081  # NodePortとして使用するポート番号
  type: NodePort
