apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-pgadmin
spec:
  storageClassName: manual
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /pgadmin
    type: Directory
