apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-rails
spec:
  storageClassName: manual
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /rails
    type: Directory
