apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-rails
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /var/rails-data
    type: DirectoryOrCreate
