apiVersion: apps/v1
kind: Deployment
metadata:
  name: rails
spec:
  selector:
    matchLabels:
      app: rails
  template:
    metadata:
      labels:
        app: rails
    spec:
      containers:
      - name: rails
        image: localhost/rails:latest
        imagePullPolicy: Never
        command:
          - bundle
          - exec
        args:
          - rails s -p 3000 -b '0.0.0.0'

        resources:
          limits:
            memory: "256Mi"
            cpu: "500m"
        ports:
        - containerPort: 3000
        env:
          - name: RAILS_ENV
            value: development
        volumeMounts:
          - name: rails-storage
            mountPath: /rails/tmp
          - name: rails-storage
            mountPath: /rails/vendor
      volumes:
        - name: rails-storage
          persistentVolumeClaim:
            claimName: pvc-rails